Dentistry-Diplom/Controllers/HomeController.cs
using Dentistry_Diplom.Data.Context;
using Dentistry_Diplom.Data.Models;
using Dentistry_Diplom.Data.Repository;
using Dentistry_Diplom.Data.ViewModels;
using Dentistry_Diplom.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Net;
using System.Runtime.ConstrainedExecution;

namespace Dentistry_Diplom.Controllers
{
    public class HomeController : Controller
    {
        DensContext db;
        private int pageSize = 6;
        private int MaxPage => (int)Math.Ceiling((decimal)db.DentistryTable.Count() / pageSize);
        public HomeController(DensContext context)
        {
            db = context;
        }

        public IActionResult Index(int category = 1, int page = 1)
        {
            PageLinkTagHelper.categoryId = category;
            ViewBag.Title = "Главная страница";
            return View(
                new DentistryPagingModel
                {
                    Dentistrys = db.DentistryTable
                    .Where(c=>c.categoryId == category)
                    .OrderBy(c=>c.id)
                    .Skip((page-1) * pageSize)
                    .Take(pageSize),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = pageSize,
                        TotalItems = db.DentistryTable.Where(c=>c.categoryId==category).Count()
                    }
                    
                });
        }
        public IActionResult AddAllDentistrys()
        {
            MockDentistrys mockDentistrys = new MockDentistrys();
            foreach (DentistryInfo dens in mockDentistrys.Dentistrys)
            {
                db.DentistryTable.Add(dens);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult SingleDentistry(int _id)
        {
            DentistryInfo dens = db.DentistryTable.Find(_id);
            ViewBag.Title = $"Просмотр консоли {dens.name}";
            return View(dens);
        }
        public IActionResult DeleteDentistry(int _id)
        {
            DentistryInfo dens = db.DentistryTable.Find(_id);
            db.DentistryTable.Remove(dens);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Dentistry-Diplom/Controllers/ShopDentController.cs
using Dentistry_Diplom.Data.Context;
using Dentistry_Diplom.Data.Models;
using Dentistry_Diplom.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using System.Threading.Tasks;

namespace Dentistry_Diplom.Controllers
{
    public class ShopDentController : Controller
    {
        private ShopDent _shopDent;
        private DensContext db;
        public ShopDentController(DensContext context, ShopDent shopDent)
        {
            _shopDent = shopDent;
            db = context;
        }

        public ViewResult Index()
        {
            var items = _shopDent.GetShopItems();
            _shopDent.shopDentItems = items;
            var obj = new ShopDentViewModel { shopDent = _shopDent };
            return View(obj);
        }

        public RedirectToActionResult AddToDent(int Id)
        {
            DentistryInfo item = db.DentistryTable.Find(Id); 
            if (item != null)
                _shopDent.AddToDent(item); 

            return RedirectToAction("Index"); 
        }
    
    }
}

Dentistry-Diplom/Views/Shared/Components/NavigationMenuViewComponent.cs
using Dentistry_Diplom.Data.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dentistry_Diplom.Views.Shared.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        DensContext db;
        public NavigationMenuViewComponent(DensContext context)
        {
            db = context;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(db.CategoryTable.OrderBy(c=>c.categoryName));
        }
    }
}

Dentistry-Diplom/Views/Home/Index.cshtml
@model Dentistry_Diplom.Data.Models.DentistryPagingModel

<div id="carouselExampleIndicators" class="carousel slide">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/img/carousel-card1.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/img/carousel-card2.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/img/carousel-card3.png" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>


<div class="jumbotron mt-5">
    <h3 class="display-4">Исключительно у нас есть такие приставки, о которых вы могли и не знать!</h3>
    <p class="lead">
        На каждого пользователя найдется свой выбор. Если человек знает чего он хочет, то обязательно найдет себе подходящий вариант
    </p>
    <hr class="my-4">
    <p>
</div>

<h3 class="mb-5 mt-5 align-content-center">Дальше идет список консолей. Приятного ознакомления!</h3>

    <div class="row">
        <div class="col col-md-2">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col col-md-10">
            <div page-model="@Model.PagingInfo" page-action=""
                 page-classes-enabled="true"
                 page-class="btn"
                 page-class-normal="btn-default"
                 page-class-selected="btn-primary"
                 class="btn-group pull-right">
            </div>
            <div class="row mt-5 mb-2">
                @{
                foreach (var dentistryInfo in Model.Dentistrys)
                    {
                        <div class="col-lg-4">
                        <img width="350" src="@dentistryInfo.img" alt="@dentistryInfo.name" />
                        <h2>@dentistryInfo.name</h2>
                        <p>@dentistryInfo.shortDesc</p>
                            <div class="container d-flex">
                            <p style="margin-right: 80px; margin-left:-10px; margin-top: 7px">Цена: @dentistryInfo.price</p>
                            <a class="btn btn-primary" style="margin-bottom:25px" href="#" onclick="location.href = '@Url.Action("SingleDentistry", "Home", new { _id = dentistryInfo.id})'">
                                    Подробнее
                                </a>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
        </div>

Dentistry-Diplom/Views/Home/SingleDentistry.cshtml
<div class="dend mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="@Model.img" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="dend-body">
                <h5 class="dend-title">@Model.name</h5>
                <p class="dend-text">@Model.longDesc</p>
                <p class="dend-text">@Model.price.ToString("c")</p>
            </div>
        </div>
        <a class="btn btn-primary mb-1" href="#" onclick="location.href = '@Url.Action("AddToDent", "ShopDent", new { id = Model.id })'">В корзину</a>
        @Html.ActionLink("Удалить", "DeleteDentistry", "Home", new { _id = Model.id },
        new { onclick = "return confirm('Вы уверены, что хотите удалить товар?')", @class = "btn btn-danger" })

    </div>
</div>