Dentistry-Diplom/Controllers/CategoryController.cs
using Dentistry_Diplom.Data.Context;
using Dentistry_Diplom.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Net;

namespace Dentistry_Diplom.Controllers
{
    public class CategoryController : Controller
    {
        private DensContext db;
        public CategoryController(DensContext context)
        {
            db = context;
        }
        public IActionResult PortativeCategory()
        {
            List<DentistryInfo> dens = db.DentistryTable.ToList();
            ViewBag.Title = "Таблица портативных консолей";
            return View(dens);
        }
        public IActionResult StationarCategory()
        {
            List<DentistryInfo> dens = db.DentistryTable.ToList();
            ViewBag.Title = "Таблица стационарных консолей";
            return View(dens);
        }
    }
}

Dentistry-Diplom/Controllers/ShopDentController.cs
using Dentistry_Diplom.Data.Context;
using Dentistry_Diplom.Data.Models;
using Dentistry_Diplom.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using System.Threading.Tasks;

namespace Dentistry_Diplom.Controllers
{
    public class ShopDentController : Controller
    {
        private ShopDent _shopDent;
        private DensContext db;
        public ShopDentController(DensContext context, ShopDent shopDent)
        {
            _shopDent = shopDent;
            db = context;
        }

        public ViewResult Index()
        {
            var items = _shopDent.GetShopItems();
            _shopDent.shopDentItems = items;
            var obj = new ShopDentViewModel { shopDent = _shopDent };
            return View(obj);
        }

        public RedirectToActionResult AddToDent(int Id)
        {
            DentistryInfo item = db.DentistryTable.Find(Id); 
            if (item != null)
                _shopDent.AddToDent(item); 

            return RedirectToAction("Index"); 
        }
    
    }
}

Dentistry-Diplom/Views/Shared/Components/NavigationMenuViewComponent.cs
using Dentistry_Diplom.Data.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dentistry_Diplom.Views.Shared.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        DensContext db;
        public NavigationMenuViewComponent(DensContext context)
        {
            db = context;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(db.CategoryTable.OrderBy(c=>c.categoryName));
        }
    }
}

Dentistry-Diplom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head data-bs-theme="dark">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/Style.css" rel="stylesheet" />
</head>
<body data-bs-theme="dark">
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Console'щик</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-theme="dark" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" onclick="location.href = '@Url.Action("Index","Home")'" href="/">Главная</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button">Категории</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#" onclick="location.href = '@Url.Action("StationarCategory", "Category")'">Стационарные</a></li>
                                <li><a class="dropdown-item" href="#" onclick="location.href = '@Url.Action("PortativeCategory", "Category")'">Портативные</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="location.href='@Url.Action("Index","ShopDent")'">Корзина</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                                Профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#" onclick="location.href = '@Url.Action("DentistryList", "Dentistry")'">Список консолей</a></li>
                                <li><a class="dropdown-item" href="#" onclick="location.href = '@Url.Action("AddAllDentistrys", "Home")'">Перегрузка БД</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container">
        @RenderBody()
    </div>
    <!-- Footer -->
    <footer class="bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4">
            <!-- Section: Text -->
            <section class="mb-4">
                <p>
                    Дополнительные и интересные ссылки вы можете найти ниже.
                    За помощью и политикой конфиденциальности вы также можете обратиться по ссылкам ниже
                </p>
            </section>
            <!-- Section: Text -->
            <!-- Section: Links -->
            <section class="">
                <!--Grid row-->
                <div class="row">
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Профили:</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">VK</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">X(Twitter)</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Other SocialMedia</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Новости:</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">Instagram</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Pinterest</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Ya.Dzen</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Важное:</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">FAQ</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Политика конф.</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Тех.Поддержка</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Проблемы:</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">Оформление возврата</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Проблемы с товаром</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Книга жалоб</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->
                </div>
                <!--Grid row-->
            </section>
            <!-- Section: Links -->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2023 Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">Консольщик.рф</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>